#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FoodWarning.Droid.Resource", IsApplication=true)]

namespace FoodWarning.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::FoodWarning.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::FoodWarning.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::FoodWarning.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::FoodWarning.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::FoodWarning.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::FoodWarning.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::FoodWarning.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::FoodWarning.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::FoodWarning.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::FoodWarning.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::FoodWarning.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::FoodWarning.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::FoodWarning.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::FoodWarning.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::FoodWarning.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::FoodWarning.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::FoodWarning.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::FoodWarning.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::FoodWarning.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::FoodWarning.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::FoodWarning.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::FoodWarning.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::FoodWarning.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::FoodWarning.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::FoodWarning.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::FoodWarning.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::FoodWarning.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::FoodWarning.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::FoodWarning.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::FoodWarning.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::FoodWarning.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::FoodWarning.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::FoodWarning.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::FoodWarning.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::FoodWarning.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::FoodWarning.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::FoodWarning.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int ahBarColor = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int ahBarLength = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int ahBarWidth = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ahCircleColor = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int ahDelayMillis = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int ahRadius = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int ahRimColor = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int ahRimWidth = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int ahSpinSpeed = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int ahText = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int ahTextColor = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int ahTextSize = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int accent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int background = 2130837505;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int background_card = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int ic_errorstatus = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int ic_launcher = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int ic_successstatus = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int roundedbg = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int roundedbgdark = 2130903045;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int image = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int linearLayout1 = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int loadingImage = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int loadingProgressBar = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int loadingProgressWheel = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int textViewStatus = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int text_caption = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int text_title = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int webview = 2130968584;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int Detail = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int loading = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int loadingimage = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int loadingprogress = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int Master = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int RSSItem = 2131034117;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int library_name = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int BaseTheme = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int Theme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000,0x7F010001,0x7F010002,0x7F010003,0x7F010004,0x7F010005,0x7F010006,0x7F010007,0x7F010008,0x7F010009,0x7F01000A,0x7F01000B }
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int ProgressWheel_ahBarColor = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahBarLength = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahBarWidth = 2;
			
			// aapt resource value: 3
			public const int ProgressWheel_ahCircleColor = 3;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahDelayMillis = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRadius = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahRimColor = 6;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahRimWidth = 7;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahSpinSpeed = 8;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahText = 9;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahTextColor = 10;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahTextSize = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
